name: Release Docker image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Setup Node
      uses: actions/setup-node@v3.4.1

    - uses: actions/checkout@v3
    - name: Setup build directory
      run: make dirs

    - name: Install Node modules
      run: npm install
    
    - name: Build client app
      run: make build/app
    
    - name: Build Go API
      run: make build/api
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/betapictoris/flagdown:${{ github.event.release.tag_name }}

    - name: Login to GitHub Container registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u BetaPictoris --password-stdin
    
    - name: Push to GitHub Containers registry
      run: docker push ghcr.io/betapictoris/flagdown:${{ github.event.release.tag_name }}
