name: Docker Image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Setup Node
      uses: actions/setup-node@v3.4.1

    - uses: actions/checkout@v3
    - name: Setup build directory
      run: make dirs

    - name: Install Node modules
      run: npm install
    
    - name: Build client app
      run: npm run build
    
    - name: Build Go API
      run: make api
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flagdown:$(git log | grep commit -m 1 | cut -f2 -d' ')